---
router-1:
    groups:
      - routers
    platform: cisco_xe
    hostname: 1.1.1.1

router-2:
    groups:
      - routers
    platform: cisco_xe
    hostname: 1.1.1.2

router-3:
    groups:
      - routers
    platform: cisco_xe
    hostname: 1.1.1.3

